#pragma once
//命名(MSG_触发消息的SDL窗口类_具体消息)

//HTTP请求后，发送的窗口消息
#define HTTPREQUESTCOMPELETE_UPDATE_DEVICEBINGSLIST	8848//设备列表请求后，设备列表更新消息

//SDL区域选择窗口消息
#define MSG_UIAREARECORD_UPDATE 6001	//SDL选区录制窗口录制区域改变-响应录制接口改变录制参数

//更多按钮呼出的SDL下拉框
#define MSG_UIDROPDOWNMENU_CAMERARECORD 7003		//摄像头录制
#define MSG_UIDROPDOWNMENU_MOUSERECORD 7004			//跟随鼠标录制
#define MSG_UIDROPDOWNMENU_SYSTEMAUDIOMICRO 7005	//声音录制

//应用程序消息
#define MSG_APPMSG_MINIMALANDTIPSRECORDING 8848	//通知应用程序最小化并弹出消息泡提示录制开始
#define MSG_APPMSG_LOGOUTSUCCESS 8849			//通知应用程序，成功退出登录时发送消息

//SDL窗口消息
#define MSG_UIDEVICEBIND_UNBINDANDCLOSE 8501	//SDL设备绑定窗口关闭
#define MSG_UIPROFILE_SIGNOUT 8502	            //SDL用户信息窗口点击了退出登录
#define MSG_UIAREARECORD_HIDEMAINDLGTORECORD 8503
#define MSG_UIAREARECORD_STARTRECORD 8504
#define MSG_UIAREARECORD_STOPRECORD 8505
#define MSG_UIAREARECORD_CLOSEWINDOW 8506
#define MSG_UIRAI_CONTINUE 8507			//SDL权益窗口点击了继续试用
#define MSG_UIRAI_OPENVIP 8508			//SDL权益窗口点击了开通会员
#define MSG_UIAREARECORD_PAUSERECORD 8509
#define MSG_UIAREARECORD_RESUMERECORD 8910

//MFC窗口消息
#define MSG_CLARLISTBOX_SELECTED 10001
#define MSG_WINDOWIMAGECAPTURE_COMPELETE 10002
#define MSG_WINDOWRECORDPAGE_CLICKAREARECORD 10003
#define MSG_WINDOWRECORDPAGE_RECORDWINDOWMINIMAL 10004
#define WM_TRAYICON 10005								//托盘消息
#define MSG_NONEVIPDLG_OPENVIP 10006					//在不是vip的提示对话框中点击了开通会员
#define MSG_NONEVIPDLG_UNBIND 10007
#define MSG_NONEVIPDLG_LOGIN 10008
#define MSG_REQUESTCONFIGDLG_CLOSE 10009
#define MSG_OPENVIPDLG_PAYMENTLOOPERROR 10010
#define MSG_LOGINDLG_UPDATEUSERINFO 10011
#define MSG_MAINDLG_COLLECTVALUME 6002
#define MSG_SCREENSHOTDLG_SHOTCOMPELETE 10012
#define MSG_TOPRECDLG_STARTRECORD 10013
#define MSG_TOPRECDLG_STOPRECORD 10014
#define MSG_CHILDDLG_TIMERCOUNTSTART 10015
#define MSG_CHILDDLG_STOPTIMERCOUNTANDSHOWNORMALUI 10016
#define MSG_USERPRIFLEDLG_WINDOWHIDDENBYTIMTER 10017
#define MSG_USERPRIFILEDLG_SHOWLOGOUTSUCCESSFULDLG 10018	//用户界面窗口点击退出登录并且成功退出登录后发送消息
#define MSG_GAMEREC_RECORDWINDOWMINIMAL 10019
#define MSG_USERPROFILE_OPENVIP	10020
#define MSG_OPENVIP_VIPPRIVILEGECONTRAST 10021
#define MSG_SEASONMEMBER_STARTPAYMENTPOLLING 10022
#define MSG_LEVELUP_STARTPAYMENTPOLLING 10023
#define MSG_LEVELUP_UPDATEUIMODELDATA 10024
#define MSG_MOUTHMEMBER_ONPAYMENTSUCCESS 10025
#define MSG_TOPRECDLG_STARTRECORD_WINDOW 10026
#define MSG_TOPRECDLG_STOPRECORD_WINDOW 10027
#define MSG_TOPRECDLG_PAUSE_WINDOW 10028
#define MSG_TOPRECDLG_RESUME_WINDOW 10029  
#define MSG_VIPDLG_LOGINSHOW 10030
#define MSG_VIPDLG_INREADPACKETMODE 10031
#define MSG_VIPDLG_UPDATESCALEWITHMODE 10032

//App消息
#define MSG_APPMSG_FIRSTOPENTOOPENVIP 11000

//其他MFC消息
#define MSG_SILDERCTRL_ISSLIDERMOVING	10020	//MFC自带的滑块控件滑到边缘

//MFC广播消息
#define BROADCASTMSG_USERLOGIN_ISLOGININ 11011
#define BROADCASTMSG_USERLOGIN_ISLOGINOUT 11012

//定时器消息
#define TIMER_MAINDLG_NEEDREDUCEBINDS 20001
#define TIMER_NONEVIP_RECORDTIME 20002
#define TIMER_TOPRECDLG_TIMECOUNT 20003

//核心功能底层消息
#define MSG_SCRENC_FILESIZEUPDATE 23231

namespace MsgParam
{
	//音量值结构体
	struct VolumeInfo
	{
		float MicroAudioVolume = -1;//麦克风音量值
		float SystemAudioVolume = -1;//系统音频音量值
	};

	// 列表框选择信息结构
	struct LISTBOX_SELECT_INFO
	{
		int nIndex;             // 选中的项目索引
		CString strText;        // 选中的项目文本
		std::wstring strBoxName; // 列表框在map中的键值
	};
}


